### ISSUE TITLE
How to build a KES Server like `https://play.min.io:7373`

### ISSUE THREAD

**Issue by zwj-coder** [minio/kes#137]
#### What is the problem you want to solve?

I want to build a KES Server which is same as `https://play.min.io:7373` just for integration test, but I failed to build it. Can someone give me some instruction, I really appreciate.
#### Additional context

1. Are there alternative solutions?

2. Would your solution cause a major breaking API change?

3. Anything else that is important?

**Comment by aead** [comment]
Our `play` instance is basically built using this guide: https://github.com/minio/kes/wiki/Filesystem-Keystore

You just have to adjust the `config.yml` slightly:
```yaml
address: 0.0.0.0:7373
root:   <$(kes tool identity of <your-root.crt)>

tls:
  key:  server.key
  cert: server.cert

keystore:
  fs:
    path: ./keys # Choose a directory for the secret keys
```
> Just set the root identity accordingly.
