### ISSUE TITLE
kes TLS Proxy on nginx-ingress kubernetes - Error: failed to connect to audit log: too many client certificates are present

### ISSUE THREAD

**Issue by rafalkasa** [minio/kes#149]
#### Bug describtion
I need help with setup kes and minio in kubernetes cluster
Finally I have problem with connection to the kes server from kes client  because of the `Error: failed to connect to audit log: too many client certificates are present`

The [TLS Proxy](https://github.com/minio/kes/wiki/TLS-Proxy) documentation is about how to configure the regular nginx but I can't find example how to configure TLS Proxy for nginx-ingress on the kubernetes.

My kes.yaml file looks like below:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kes
spec:
  ports:
  - port: 7373
    name: kes-api-tcp
    protocol: TCP    
    targetPort: 7373 
  selector:
    app: kes
    role: server
  type: ClusterIP  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kes-local-config
data:
  local.config: |
    address: 0.0.0.0:7373
    root: disabled  # We disable the root identity since we don't need it in this guide
    tls:
      key: /keys/server-key.pem
      cert: /keys/server.pem   
      proxy:
        identities:
        - <nginx-proxy-cert-identities>
        header:
          cert: X-Tls-Client-Cert
    policy:
      my-policy:
        paths:
        - /v1/key/create/*
        - /v1/key/generate/*
        - /v1/key/decrypt/*
        - /v1/key/delete/*
        identities:
        - <kes-client-cert-identities>
    keys:
      vault:
        endpoint: http://vault:8200
        approle:
          id:     "<app-role-id>" # Your AppRole ID
          secret: "<app-role-secret> # Your AppRole Secret ID
          retry:  15s
        status:
          ping: 10s
        tls:
          ca: /keys/ca.pem # Since we use self-signed certificates
    log:
      error: on
      audit: on 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kes
  labels:
    app: kes
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kes
      role: server
  template:
    metadata:
      labels:
        app: kes
        role: server
    spec:
      containers:
      - name: kes
        image: minio/kes:v0.16.1
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        args: [ "server", "--config=/config/server-config.yml", "--auth=off" ]
        ports:
        - containerPort: 7373
          name: api
        volumeMounts:
        - mountPath: "/keys/server.pem"
          name: kes-cert
          subPath: server.pem
          readOnly: true
        - mountPath: "/keys/server-key.pem"
          name: kes-key
          subPath: server-key.pem
          readOnly: true
        - mountPath: "/keys/ca.pem"
          name: kes-ca
          subPath: ca.pem
          readOnly: true
        - mountPath: /config 
          name: kes-config-volume
          readOnly: true                   
      volumes:
      - name: kes-key  
        secret:
          secretName: kms-key-file
      - name: kes-cert  
        secret:
          secretName: kms-cert-file
      - name: kes-ca  
        secret:
          secretName: kms-ca-file
      - name: kes-config-volume
        configMap:
          name: kes-local-config
          items:
          - key: local.config
            path: server-config.yml
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kes
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "default/nginx-proxy-tls-key-file"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Tls-Client-Cert $ssl_client_escaped_cert; 
      proxy_ssl_name "kes.default.svc.cluster.local";
spec:
  tls:
  - secretName: my-server-cert
  rules:
  - host: kes.my-server.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kes
            port: 
              number: 7373      
```      

### Finally when I try to connect from kes client:
`export KES_SERVER=https://kes.my-server.com`
`export KES_CLIENT_CERT=root.cert`
`export KES_CLIENT_KEY=root.key`

`kes log trace  -k`

`Error: failed to connect to audit log: too many client certificates are present`

On the kes server (pod console-log) I received log as below:

```
Authenticating to Hashicorp Vault 'http://vault:8200' ... 
Endpoint: https://127.0.0.1:7373        https://10.1.152.68:7373      

Root:     _     [ disabled ]
Auth:     off   [ any client can connect but policies still apply ]

Keys:     Hashicorp Vault: http://vault:8200

CLI:      export KES_SERVER=https://127.0.0.1:7373
          export KES_CLIENT_KEY=<client-private-key>   // e.g. $HOME/root.key
          export KES_CLIENT_CERT=<client-certificate>  // e.g. $HOME/root.cert
          kes --help
{"time":"2021-09-13T19:03:32Z","request":{"path":"/v1/log/audit/trace","identity":""},"response":{"code":400,"time":86461}}
{"time":"2021-09-13T19:18:24Z","request":{"path":"/v1/log/audit/trace","identity":""},"response":{"code":400,"time":64211}}
```
