### ISSUE TITLE
`prefix` does not take effect for Vault Keystore configuration

### ISSUE THREAD

**Issue by staelen** [minio/kes#178]
#### Bug description
For version 0.17.4, in `kes.yml`

```
...
keystore:
  vault:
    endpoint: http://vault.internal:8200
    prefix: staging
    approle:
      engine: staging/approle
      id: ""
      secret: ""
      retry: 15s
    status:
      ping: 10s
...
```

#### Expected behavior
Expected kes to fire to `http://vault.internal:8200/v1/kv/staging/key-name`, but it fired to `http://vault.internal:8200/v1/kv/key-name` instead, ignoring what is set in the `prefix` key.

#### Additional context

1. What version of Go are you using (`go version`)?

`go version go1.15.14 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

`RHEL 7.9 amd64`

3. Anything else that is important?

We downgraded from v0.17.4 to v0.17.2 and it's working again. We are not proficient with Go but we combed through the code and it seems very likely that this commit [a229d68](https://github.com/minio/kes/commit/a229d68fd98192ab4df32c296ab5febec172f5b8) broke the feature, especially [here](https://github.com/minio/kes/blob/master/internal/vault/config.go#L154) where we saw that `prefix` are not being returned in the cloned object.
