### ISSUE TITLE
Policies not working after upgrading to v0.17.5

### ISSUE THREAD

**Issue by staelen** [minio/kes#180]
#### Bug description
For version 0.17.5, in `kes.yml`

```
...
policy:
  staging-minio:
    allow:
    - /v1/key/create/key-name
    - /v1/key/generate/key-name
    - /v1/key/decrypt/key-name
    identities:
    - value-of-minio-certificate
...
```

#### Expected behavior
While trying to authenticate a client using a policy, we are getting "prohibited by policy" in audit logs after upgrading to v0.17.5 without any changes to our `kes.yml`. We've checked and it seems that the policy is correct according to the documentation, and also that the correct identity was being used according to the audit logs.

#### Additional context

1. What version of Go are you using (`go version`)?

`go version go1.15.14 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?

`RHEL 7.9 amd64`

3. Anything else that is important?

We've downgraded from v0.17.5 to v0.17.2 and it's working again. We are wondering if [this](https://github.com/minio/kes/blob/a229d68fd98192ab4df32c296ab5febec172f5b8/internal/yml/server-config_v0.17.0.go#L25) should be `yaml:identities` instead of `yaml:identity` since the key name in the yaml should be `identities`
