### ISSUE TITLE
KES refuses connection from MinIO : x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by GorgetGuilhem** [minio/kes#279]
#### Bug describtion
I'm currently trying to build a production full encrypted MinIO - KES - Vault system with docker compose. Nginx is used as reverse proxy for all applications. Despite all my attempts, KES is still refusing the connection from MinIO with slef-signed mTLS certificates. MinIO refuses to launch as Nginx returns `502 - Bad Gateway`, certainly because of KES refusing to accept the connection. Logs are attached bellow :

```Copyright  MinIO, Inc.  https://min.io
License    GNU AGPLv3   https://www.gnu.org/licenses/agpl-3.0.html
Version    v0.21.1      linux/amd64

KMS        Hashicorp Vault: https://vault.test.example
Endpoints  https://127.0.0.1:7373
           https://172.24.0.3:7373

Admin      _            [ disabled ]
mTLS       verify       Only clients with trusted certificates can connect
Mem Lock   on           RAM pages will not be swapped to disk

{"message":"2022/10/26 12:10:45 http: TLS handshake error from 172.24.0.7:56364: tls: failed to verify client certificate: x509: certificate signed by unknown authority"}
```

#### Expected behavior
I would expect KES to accept MinIO connection, or at least a clearer documentation about TLS proxying.

#### Additional context
TLS certificates have been issued with certbot with this logic :
```
certbot certonly --standalone -d vault.test.example --staple-ocsp -m <email> --agree-tos
```

mTLS certificates have been issued with a private CA following this guide : https://jamielinux.com/docs/openssl-certificate-authority/introduction.html

Chain of trust for both server and client mTLS certificates seems to be good :
```
openssl verify -show_chain -CAfile ca/certs/ca.cert.pem -untrusted ca/intermediate/certs/intermediate.cert.pem nginx/certs/nginx-kes-server.cert.pem 
nginx/certs/nginx-kes-server.cert.pem: OK
Chain:
depth=0: C = FR, ST = France, L = Paris, O = Alice LTD, OU = IT, CN =  Alice LTD Nginx KES server, emailAddress = alice@alice-ltd.com (untrusted)
depth=1: C = FR, ST = France, O = Alice LTD, OU = IT, CN = Alice LTD Intermediate CA, emailAddress = alice@alice-ltd.com (untrusted)
depth=2: C = FR, ST = France, L = France, O = Alice LTD, OU = IT, CN = Alice LTD Root CA, emailAddress = alice@alice-ltd.com
```

```
openssl verify -show_chain -CAfile ../ca/certs/ca.cert.pem -untrusted ../ca/intermediate/certs/intermediate.cert.pem minio/certs/minio-kes-client.cert.pem 
minio/certs/minio-kes-client.cert.pem: OK
Chain:
depth=0: C = FR, ST = France, L = Grenoble, O = Alice LTD, OU = IT, CN = Alice LTD Minio KES client, emailAddress = alice@alice-ltd.com (untrusted)
depth=1: C = FR, ST = France, O = Alice LTD, OU = IT, CN = Alice LTD Intermediate CA, emailAddress = alice@alice-ltd.com (untrusted)
depth=2: C = FR, ST = France, L = Grenoble, O = Alice LTD, OU = IT, CN = Alice LTD Root CA, emailAddress = alice@alice-ltd.com
```

`ca-chain.cert.pem` is OK too:
```
openssl verify -CAfile ca/certs/ca.cert.pem ca/intermediate/certs/intermediate.cert.pem
../ca/intermediate/certs/intermediate.cert.pem: OK
```

Certificates order in `ca-chain.cert.pem` seems right as I concatenated them with:
```
cat intermediate/certs/intermediate.cert.pem certs/ca.cert.pem > intermediate/certs/ca-chain.cert.pem
```

As seen in https://github.com/minio/kes/wiki/Concepts, client certificate `minio-kes-client.cert.pem` contains a Extended Key Usage containing `Client Authentication` and server certificate `nginx-kes-server.cert.pem` contains Extended Key Usage containing `Server Authentication`.

Vault is up, running and unsealed.

`docker-compose.yml`:
```
version: '3.9'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
  command: server --console-address ":9001" http://minio{1...4}/data1 --certs-dir "/miniocerts"
  expose:
    - "9000"
    - "9001"
  secrets:
    - access_key
    - secret_key
  environment:
    MINIO_KMS_KES_ENDPOINT: https://kes.test.example
    MINIO_KMS_KES_CERT_FILE: /certs/minio-kes-client.cert.pem
    MINIO_KMS_KES_KEY_FILE: /certs/minio-kes-client.key.pem
    MINIO_KMS_KES_CAPATH: /certs/CAs/ca-chain.cert.pem
    MINIO_KMS_KES_KEY_NAME: minio-key
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    container_name: minio1
    hostname: minio1
    volumes:
      - data1-1:/data1
      - ./ca/certs/ca-chain.cert.pem:/certs/CAs/ca-chain.cert.pem:ro
      - ./minio/certs/minio-kes-client.cert.pem:/certs/minio-kes-client.cert.pem:ro
      - ./minio/certs/minio-kes-client.key.pem:/certs/minio-kes-client.key.pem:ro

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - data2-1:/data1
      - ./ca/certs/ca-chain.cert.pem:/certs/CAs/ca-chain.cert.pem:ro
      - ./minio/certs/minio-kes-client.cert.pem:/certs/minio-kes-client.cert.pem:ro
      - ./minio/certs/minio-kes-client.key.pem:/certs/minio-kes-client.key.pem:ro

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    volumes:
      - data3-1:/data1
      - ./ca/certs/ca-chain.cert.pem:/certs/CAs/ca-chain.cert.pem:ro
      - ./minio/certs/minio-kes-client.cert.pem:/certs/minio-kes-client.cert.pem:ro
      - ./minio/certs/minio-kes-client.key.pem:/certs/minio-kes-client.key.pem:ro

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - data4-1:/data1
      - ./ca/certs/ca-chain.cert.pem:/certs/CAs/ca-chain.cert.pem:ro
      - ./minio/certs/minio-kes-client.cert.pem:/certs/minio-kes-client.cert.pem:ro
      - ./minio/certs/minio-kes-client.key.pem:/certs/minio-kes-client.key.pem:ro

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    hostname: nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ca/certs/ca-chain.cert.pem:/ca/certs/ca-chain.cert.pem:ro
      - ./nginx/certs/nginx-kes-server.cert.pem:/nginx/certs/nginx-kes-server.cert.pem:ro
      - ./nginx/certs/nginx-kes-server.key.pem:/nginx/certs/nginx-kes-server.key.pem:ro
      - /etc/letsencrypt/live/vault.test.example/fullchain.pem:/vault/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/vault.test.example/privkey.pem:/vault/certs/privkey.pem:ro
      - /etc/letsencrypt/live/kes.test.example/fullchain.pem:/kes/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/kes.test.example/privkey.pem:/kes/certs/privkey.pem:ro
      - /etc/letsencrypt/live/minio-api.test.example/fullchain.pem:/minio/certs/api/fullchain.pem:ro
      - /etc/letsencrypt/live/minio-api.test.example/privkey.pem:/minio/certs/api/privkey.pem:ro
      - /etc/letsencrypt/live/minio-console.test.example/fullchain.pem:/minio/certs/console/fullchain.pem:ro
      - /etc/letsencrypt/live/minio-console.test.example/privkey.pem:/minio/certs/console/privkey.pem:ro
    ports:
      - 80:80
      - 443:443

  vault:
    image: vault:1.12.0
    container_name: vault
    restart: always
    volumes:
      - ./vault/config/config.hcl:/vault/config/vault.hcl:ro
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
    cap_add:
      - IPC_LOCK
    entrypoint: "vault server -config /vault/config/config.hcl"
    networks:
      default:
        aliases:
          - vault

  kes:
    container_name: kes
    hostname: kes
    image: minio/kes:v0.21.1
    volumes:
      - ./kes/config/config.yml:/root/.kes/config/kes.yml:ro
      - /etc/letsencrypt/live/kes.test.example/fullchain.pem:/root/.kes/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/kes.test.example/privkey.pem:/root/.kes/certs/privkey.pem:ro
    cap_add:
      - IPC_LOCK
    command: server --config /root/.kes/config/config.yml
    expose:
      - "7373"
    depends_on:
      - vault

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data2-1:
  data3-1:
  data4-1:

secrets:
  access_key:
    file: ./secrets/access_key
  secret_key:
    file: ./secrets/secret_key
```

`kes.yml`:
```
address: 0.0.0.0:7373

admin:
  identity: disabled

tls:
  key: /root/.kes/certs/privkey.pem
  cert: /root/.kes/certs/fullchain.pem

  proxy:
    identities:
    - <nginx-kes-server.cert.pem identity>
    header:
      cert: X-Tls-Client-Cert

cache:
  expiry:
    any:    1m0s
    unused: 20s

policy:
  minio:
    allow:
      - /v1/key/create/*
      - /v1/key/generate/*
      - /v1/key/decrypt/*
      - /v1/key/list/*
      - /v1/identity/list/*
    identities:
      - <minio-kes-client.cert.pem identity>

keystore:
  vault:
    endpoint: https://vault.test.example
    version: v1
    approle:
      id: <approle_id>
      secret: <approle_secret_id>
      retry: 15s
    status:
      ping: 10s

log:
  error: on
  audit: on
```

`nginx.conf`:
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

     upstream minio {
         server minio1:9000;
         server minio2:9000;
         server minio3:9000;
         server minio4:9000;
     }

     upstream console {
         ip_hash;
         server minio1:9001;
         server minio2:9001;
         server minio3:9001;
         server minio4:9001;
     }

     server {
         listen       443 ssl;
         listen  [::]:443 ssl;
         server_name  minio-api.test.example;
         error_page 497 https://$server_name:$server_port$request_uri;
         ignore_invalid_headers off;
         client_max_body_size 0;
         proxy_buffering off;
         proxy_request_buffering off;
         ssl_certificate      /minio/certs/api/fullchain.pem;
         ssl_certificate_key  /minio/certs/api/privkey.pem;
         ssl_protocols TLSv1.2 TLSv1.3;
         ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
         ssl_prefer_server_ciphers off;
         location / {
             proxy_set_header Host $http_host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
             proxy_connect_timeout 300;
             proxy_http_version 1.1;
             proxy_set_header Connection "";
             chunked_transfer_encoding off;
             proxy_pass http://minio;

         }
     }

     server {
        listen       443 ssl;
        listen  [::]:443 ssl;
        server_name  minio-console.test.example;
        error_page 497 https://$server_name:$server_port$request_uri;
        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_buffering off;
        proxy_request_buffering off;
        ssl_certificate      /minio/certs/console/fullchain.pem;
        ssl_certificate_key  /minio/certs/console/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;
            real_ip_header X-Real-IP;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            chunked_transfer_encoding off;
            proxy_pass http://console;
        }
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name  vault.test.example;
        error_page 497 https://$server_name:$server_port$request_uri;
        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_buffering off;
        proxy_request_buffering off;
        ssl_certificate      /vault/certs/fullchain.pem;
        ssl_certificate_key  /vault/certs/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;
            real_ip_header X-Real-IP;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
            proxy_pass http://vault:8200;
        }
    }

    server {
        listen       443 ssl http2;
        listen  [::]:443 ssl http2;
        server_name  kes.test.example;
        error_page 497 https://$server_name:$server_port$request_uri;
        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_request_buffering off;
        ssl_certificate      /kes/certs/fullchain.pem;
        ssl_certificate_key  /kes/certs/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        ssl_verify_client optional_no_ca;
        location / {
            proxy_buffering off;

            # Tried with and without
            proxy_ssl_server_name on;

            proxy_ssl_certificate         /nginx/certs/nginx-kes-server.cert.pem;
            proxy_ssl_certificate_key     /nginx/certs/nginx-kes-server.key.pem;
            proxy_ssl_trusted_certificate /ca/certs/ca-chain.cert.pem;
            proxy_set_header X-Tls-Client-Cert $ssl_client_escaped_cert;
            proxy_ssl_verify on;

            # Tried with and without
            proxy_ssl_verify_depth 2;

            # Tried with and without
            proxy_ssl_session_reuse on;

            proxy_ssl_protocols TLSv1.3;
            proxy_pass https://kes:7373;
        }
    }
}
```

MinIO docker image: RELEASE.2022-10-24T18-35-07Z
KES docker image: 0.21.1
Vault docker image: 1.12.0
Nginx docker image: stable-alpine

**Comment by aead** [comment]
Based on the issue description, I assume starting KES with the `--auth off` flag works.
Hence, the issue seems to be that KES fails to verify nginx client certificate.

Have you tried connecting MinIO directly to KES without nginx?
Is `intermediate/certs/ca-chain.cert.pem` part of the system CAs on the node running KES. KES uses the system CA roots to verify a certificate.

**Comment by GorgetGuilhem** [comment]
Absolutely, everything works properly with the `--auth off` flag. I've not tried connecting MinIO directly to KES but I can give it a try !

It is, I've installed it to the node system CA by copying the cert into `/usr/local/share/ca-certificates/` and running `update-ca-certificates`.

**Comment by GorgetGuilhem** [comment]
Hi, I did what you suggested and removed the nginx reverse-proxy part of the installation. Now kes and minio are complaining about bad certificates.

Kes logs :
```
{"message":"2022/11/18 11:23:37 http: TLS handshake error from 172.20.0.5:38672: remote error: tls: bad certificate"}
{"message":"2022/11/18 11:23:37 http: TLS handshake error from 172.20.0.4:59406: tls: failed to verify client certificate: x509: certificate signed by unknown authority"}
```

Minio logs :
```
ERROR Unable to initialize a connection to KES as specified by the shell environment: Post "https://kes:7373/v1/key/create/minio-alice-key": x509: certificate signed by unknown authority
```

I've included my ca-chain.crt into the KES server :
```
mv /tmp/ca-chain.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust
```

I've checked again my certificates and I don't see any mistake on this side but I can provide them in case that helps !

**Comment by GorgetGuilhem** [comment]
Hi, is there something new from your side ?

**Comment by aead** [comment]
Can you curl the KES server - like `curl --key <private.key> --cert <client-cert> --ca-cert <server-crt> 'https://kes:7373/v1/api`

An alternative solution to updating the system CAs may be: https://github.com/minio/kes/blob/master/server-config.yaml#L29

**Comment by GorgetGuilhem** [comment]
Here is the output of `curl --key minio/certs/minio.key.pem --cert minio/certs/minio.cert.pem --cacert ca/certs/cacert.pem 'https://kes:7373/v1/api' -v` :
```
*   Trying 172.20.0.7:7373...
* Connected to kes (172.20.0.7) port 7373 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: ca/certs/cacert.pem
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=FR; ST=Auvergne Rhône-Alpes; O=Adlin-Science; OU=Adlin-Science IT; CN=KES Server
*  start date: Dec 16 16:23:11 2022 GMT
*  expire date: Jun 23 16:23:11 2027 GMT
*  subjectAltName: host "kes" matched cert's "kes"
*  issuer: C=FR; ST=Ile-De-France; L=Paris; O=Alice LTD; OU=Alice LTD IT; CN=Alice LTD Root CA; emailAddress=alice@example.com
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x5557d18257d0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /v1/api HTTP/2
> Host: kes:7373
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS alert, bad certificate (554):
* OpenSSL SSL_read: error:0A000412:SSL routines::sslv3 alert bad certificate, errno 0
* Failed receiving HTTP2 data
* OpenSSL SSL_write: SSL_ERROR_ZERO_RETURN, errno 0
* Failed sending HTTP2 data
* Connection #0 to host kes left intact
curl: (56) OpenSSL SSL_read: error:0A000412:SSL routines::sslv3 alert bad certificate, errno 0
```

I already tried to add the ca in the config file, it doesn't change anything. I also verified the config file is properly sourced, KMS endpoint is perfectly read from the file.

**Comment by GorgetGuilhem** [comment]
In case that could help, here are the certificates. I tried a lot of different certificates so don't pay attention to names.

<details open>
<summary>ca-chain.cert.pem</summary>

 ```
Issuer: C=FR, ST=France, L=Paris, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Root CA/emailAddress=alice@example.com
        Validity
            Not Before: Oct 20 08:05:36 2022 GMT
            Not After : Oct 17 08:05:36 2032 GMT
        Subject: C=FR, ST=France, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Intermediate CA/emailAddress=alice@example.com
        Issuer: C=FR, ST=France, L=Paris, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Root CA/emailAddress=alice@example.com
        Validity
            Not Before: Oct 20 07:57:37 2022 GMT
            Not After : Oct 15 07:57:37 2042 GMT
        Subject: C=FR, ST=France, L=Paris, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Root CA/emailAddress=alice@example.com
```

</details>

<details open>
<summary>kes-client.cert.pem</summary>

```
Issuer: C=FR, ST=France, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Intermediate CA/emailAddress=emailAddress=alice@example.com
        Validity
            Not Before: Nov 17 15:07:45 2022 GMT
            Not After : Nov 27 15:07:45 2023 GMT
        Subject: C=FR, ST=France, L=Paris, O=Alice LTD, OU=Alice LTD IT, CN=KES Client/emailAddress=alice@example.com
```

</details>

<details open>
<summary>kes-server.cert.pem</summary>

```
Issuer: C=FR, ST=France, O=Alice LTD, OU=Alice LTD IT, CN=Alice LTD Intermediate CA/emailAddress=alice@example.com
        Validity
            Not Before: Nov 18 08:31:54 2022 GMT
            Not After : Nov 28 08:31:54 2023 GMT
        Subject: C=FR, ST=France, L=Paris, O=Alice LTD, OU=Alice LTD IT, CN=KES Server/emailAddress=alice@example.com
            X509v3 Subject Alternative Name:
                DNS:kes
```

</details>

Output of `openssl verify -CAfile intermediate/certs/ca-chain.cert.pem intermediate/certs/kes-client.cert.pem` :
```
intermediate/certs/kes-client.cert.pem: OK
```

Output of `openssl verify -CAfile intermediate/certs/ca-chain.cert.pem intermediate/certs/kes-server.cert.pem`:
```
intermediate/certs/kes-server.cert.pem: OK
```

Using these certs in `config.yml` like this :
```yaml
tls:
  key: /certs/kes-server.key.pem
  cert: /certs/kes-server.cert.pem
  ca: /certs/ca-chain.cert.pem
```

And finally, lauching the server with `kes server --config /root/.kes/config/config.yml`.

I have honestly no clue at this point since the certificates seem correct.

**Comment by GorgetGuilhem** [comment]
Hi, is there any update on this ?

**Comment by krake-r** [comment]
Also a problem for me where `proxy_ssl_verify on` under pretty much the exact same scenario.

**Comment by oleynikd** [comment]
I'm having the same issue even with the `server --auth=off` option

**Comment by engelnico** [comment]
Same problem here, i've been stuck here for a couple of days. are there any updates?

**Comment by GorgetGuilhem** [comment]
Still no updates although I opened this issue three months ago. I've tried everything I could with no result, so right now I abandoned the idea of encrypting data with KES and Vault, it will be filesystem based encryption until I got some new elements.

**Comment by engelnico** [comment]
After troubleshooting for like the last 10 hours I got it working. I don't know if our issues are actually related, but I'm going to walk through my setup anyways, maybe it'll help you as well:

I tried to reduce it to a minimal working example to rule out any third-party problems, therefore I used a file-based key store. But it also works when using vault as a key store.

My folder structure is as follows: 
```tree
my-app/
├─ minio-kes/
│  ├─ certs/
│  │  ├─ kes/
│  │  │  ├─ server.crt
│  │  │  ├─ server.key
│  │  ├─ minio/
│  │  │  ├─ client.crt
│  │  │  ├─ client.key
│  ├─ config/
│  │  ├─ kes-config.yaml
│  ├─ fs/
│  ├─ minio/
├─ docker-compose.yaml
```

My docker-compose.yaml:

```yaml
version: '3.7'

services:
  minio-kes:
    image: minio/kes:latest
    container_name: minio-kes
    cap_add:
      - IPC_LOCK
    ports:
      - 7373:7373
    volumes:
      - ./minio-kes/certs:/certs
      - ./minio-kes/fs:/keys
      - ./minio-kes/config:/config
    command: server --config /config/kes-config.yaml --auth off

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-kes/minio:/data
      - ./minio-kes/certs:/certs
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_KMS_KES_ENDPOINT: https://minio-kes:7373
      MINIO_KMS_KES_CERT_FILE: /certs/minio/client.crt
      MINIO_KMS_KES_KEY_FILE: /certs/minio/client.key
      MINIO_KMS_KES_KEY_NAME: minio-default-key
      MINIO_KMS_KES_CAPATH: /certs/kes/server.crt
    command: server /data --console-address ":9001"
```



I got the ```x509: certificate signed by unknown authority``` error when I generated by certificates according to the official docs: https://min.io/docs/minio/container/operations/server-side-encryption/configure-minio-kes-hashicorp.html and https://github.com/minio/kes/wiki/MinIO-Object-Storage, where the following commands were recommended:

```bash
identity new --ip "127.0.0.1" --ip "172.19.0.2" --ip "172.19.0.2" --dns localhost --dns minio --dns minio-kes --key=/certs/kes/server.key --cert=/certs/kes/server.crt

identity new --ip "127.0.0.1" --ip "172.19.0.2" --ip "172.19.0.2" --dns localhost --dns minio --dns minio-kes --key=/certs/minio/client.key --cert=/certs/minio/client.crt
```

I actually ran these commands from the docker-compose.yaml file above and added the dns and ip flags to cover all possible docker network settings. Just to be sure...

When if verified the generated keys and certs, I got an error that the public key could not be loaded:
```bash
$ openssl x509 -in server.crt -noout -text
```

<pre><code>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            76:44:78:d0:bb:59:d7:c0:34:0a:ff:20:95:f2:15
    Signature Algorithm: Ed25519
        Issuer: CN=592f9a378a2ef51b1fd63f299db054e0358567e1d5f9b13cd0cc784aaa45f2
        Validity
            Not Before: Mar  5 17:13:54 2023 GMT
            Not After : Jun  3 17:13:54 2023 GMT
        Subject: CN=592f9a378a2ef51b1fd63f299db054e0358567e1d5f9b13cd0cc784aaa45f2
        Subject Public Key Info:
            Public Key Algorithm: Ed25519
            <strong>Unable to load Public Key
140704504346240:error:06FFF09C:digital envelope routines:CRYPTO_internal:unsupported algorithm:/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/evp/p_lib.c:250:
140704504346240:error:0BFFF06F:x509 certificate routines:CRYPTO_internal:unsupported algorithm:/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/asn1/x_pubkey.c:197:</strong>
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name: 
                DNS:minio, DNS:minio-kes, IP Address:172.19.0.2, IP Address:172.19.0.2
    Signature Algorithm: Ed25519
         83:cd:e3:e2:65:04:5a:b6:af:5a:ea:fc:e3:fd:58:d1:4a:
         4a:15:7e:f4:11:ab:71:16:92:15:c3:e2:13:11:75:33:2a:
         9b:ff:65:d0:8a:09:06:c4:3b:96:fe:e3:d3:5f:87:95:a1:
         49:bb:1b:0c:8c:7e:dd:9d:71:05
</code></pre>

When I generated my own certificate for the kes-server and the minio client with
```
openssl req -x509 -nodes -days 1095 -newkey rsa:4096 -addext "subjectAltName = IP:127.0.0.1,IP:172.19.0.2,IP:172.19.0.3,DNS:localhost,DNS:minio,DNS:minio-kes,DNS:host.docker.internal" -addext "extendedKeyUsage = serverAuth" -keyout server.key -out server.crt
```
and
```
openssl req -x509 -nodes -days 1095 -newkey rsa:4096 -addext "subjectAltName = IP:127.0.0.1,IP:172.19.0.2,IP:172.19.0.3,DNS:localhost,DNS:minio,DNS:minio-kes,DNS:host.docker.internal" -addext "extendedKeyUsage = serverAuth" -keyout client.key -out client.crt
```
respectively, I got it working. The identity of the client certificate can be retrieved as usual:
```
kes identity of /certs/client.crt
```

For reference, my kes-config.yaml file
```yaml
address: 0.0.0.0:7373 # Listen on all network interfaces on port 7373

admin:
  identity: disabled  # We disable the admin identity since we don't need it in this guide 
   
tls:
  key: /certs/kes/server.key    # The KES server TLS private key
  cert: /certs/kes/server.crt    # The KES server TLS certificate
   
policy:
  minio: 
    allow:
    - /v1/identity/*
    - /v1/key/create/minio-*
    - /v1/key/generate/minio-*
    - /v1/key/decrypt/minio-*
    - /v1/key/list/*
    identities:
    - xxxxx # Use the identity of your client.crt
   
keystore:
  fs:
    path: ./keys # Choose a directory for the secret keys

log:
  error: on
  audit: on 
```

Here, I noticed that i had to add the ```/v1/key/list/*``` path to the minio policy, otherwise the minio server could not retrieve the key list.

This is my current working setup. So I guess the problem is that the kes cli is buggy and the kes identity tool produces faulty certificates.

I guess since you generated your certificates on your own, this guide won't actually help you. I just wanted to chime in, that it is possible to get a working minio -> kes setup for data at rest encryption.

I'm by no means an expert, and I can't really follow your certificate chains, but during my troubleshooting I got the x509: unknown authority error while I was using the wrong ```MINIO_KMS_KES_CAPATH``` env variable in my minio setup. I was referencing an old kes certificate that wasn't in use anymore, so maybe try to look at that chain again.
