### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by alifiroozi80** [minio/kes#356]
Hello guys,
I'm new to the Minio and I deploy it successfully (Linux server).
I have a Vault cluster (With TLS enabled on it) as well and I want to enable [Server-Side Encryption](https://min.io/docs/minio/linux/administration/server-side-encryption.html) with Vault.

I went through the [Docs](https://min.io/docs/minio/linux/operations/server-side-encryption/configure-minio-kes-hashicorp.html#minio-sse-vault).

Here is my steps:

---

1) I installed the `KES`
2) I config the Vault server as the docs said
3) Config the Kes as the Docs said

Here is the `/opt/kes/config/kes-config.yaml`:

```yaml
address: 0.0.0.0:7373

# Disable the root administrator identity, as we do not need that level of access for
# supporting SSE operations.
admin:
  identity: disabled

# Specify the TLS keys generated in the previous step here
# For production environments, use keys signed by a known and trusted
# Certificate Authority (CA).
tls:
  key:  /opt/kes/certs/kes-server.key
  cert: /opt/kes/certs/kes-server.cert

# Sets access policies for KES
# The `minio` policy grants access to the listed APIs.
policy:
  minio:
    allow:
    - /v1/key/create/*   # You can replace these wildcard '*' with a string prefix to restrict key names
    - /v1/key/generate/* # e.g. '/minio-'
    - /v1/key/decrypt/*
    - /v1/key/bulk/decrypt
    - /v1/key/list
    - /v1/status
    - /v1/metrics
    - /v1/log/audit
    - /v1/log/error
    identities:
    - 56771b151b3301d9351a931e27e20fd97689f7c06cc7c7c21c11b4c1a72e8c2e

# Specify the connection information for the Vault server.
# The endpoint should be resolvable from the host.
# This example assumes that Vault is configured with an AppRole ID and
# Secret for use with KES.
keystore:
  vault:
    endpoint: https://vault.mydomain.com
    engine: "/minio" # Replace with the path to the K/V Engine
    version: "v2" # Specify v1 or v2 depending on the version of the K/V Engine
    approle:
      id: "e66452bb-2750-56e0-6a6d-1d5f20736653"     # Hashicorp Vault AppRole ID
      secret: "023d4898-0a60-7e85-4fb8-a36edc870ee6" # Hashicorp Vault AppRole Secret ID
      retry: 15s
    status:
      ping: 10s
    # Required if Vault uses certificates signed by an unknown CA,
    # e.g. self-signed or internal (non-globally trusted).
    # Replace this value with the full path to the Vault CA certificate.
    tls:
      ca: /home/ubuntu/vault.crt
```

Here is the `/opt/minio/config/minio`:

```yaml
# Add these environment variables to the existing environment file

MINIO_KMS_KES_ENDPOINT=https://172.16.0.105:7373
MINIO_KMS_KES_CERT_FILE=/opt/minio/certs/minio-kes.cert
MINIO_KMS_KES_KEY_FILE=/opt/minio/certs/minio-kes.key

# Allows validation of the KES Server Certificate (Self-Signed or Third-Party CA)
# Change this path to the location of the KES CA Path
MINIO_KMS_KES_CAPATH=/opt/kes/certs/kes-server.cert

# Sets the default KMS key for the backend and SSE-KMS/SSE-S3 Operations)
MINIO_KMS_KES_KEY_NAME=minio-backend-default-key

# Optional, defines the name for the KES server enclave to use.
# MINIO_KMS_KES_ENCLAVE=<name>
```

---

As you noticed in my `/opt/kes/config/kes-config.yaml` I added the certificate of my Vault cluster to the Kes config.

But when I want to start the Kes, it returns an Error:

```shell
$ sudo kes server --auth=off --config=/opt/kes/config/kes-config.yaml
Error: Put "https://vault.mydomain.com/v1/auth/approle/login": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

I even passed the Vault CA instead of its CRT but the same error still happens.

What should I do?
