### ISSUE TITLE
Kubernetes JWT path is breaked

### ISSUE THREAD

**Issue by sebglon** [minio/kes#361]
#### Bug describtion
Latest version stable: 2023-02-15T14-54-37Z

After this version, the kubernetes JWT field set with a file path not work well.
Kes read the file well but on the log we have this error:
```
 Error: open <WITHthe K8S token>: file name too long
```
On the log, the server try to open a file with the Token value.

#### Expected behavior

The JWT token is read only once and well used.

#### Additional context
```
    keystore:
      vault:
        endpoint: https://vault.vault.svc.cluster.local:8200
        prefix:   encryption-keys
        kubernetes:
          engine: ""
          role: kes
          jwt: /var/run/secrets/kubernetes.io/serviceaccount/token
          retry: 15s  # Duration until the server tries to re-authenticate after connection loss.
        status:
          ping: 10s
        tls:
          ca: /vault/secrets/vault.crt
```
