### ISSUE TITLE
Unable to use vault when secret backend is in non-standard location

### ISSUE THREAD

**Issue by psevestre** [minio/kes#55]
The Vault provider seems to add hardcoded "/kv" prefix to the supplied location:

https://github.com/minio/kes/blob/5de0d193377e0373cf769b6daec7ed316bbba191/internal/vault/vault.go#L159

This is a problem when we have more than one KV secret engine mounted on Vault or one choose to use a non-standard path.

I think the easiest thing to do here would be to simply not add the prefix, leaving to the user the liberty to specify the location. Another option would be to add another option to specify this prefix, with "kv" being its default value.

**Comment by aead** [comment]
Thanks for filing this bug report @psevestre 
Indeed, the vault provider implementation does not allow different K/V secret engines other then the "default" one.

For reference: https://www.vaultproject.io/api/secret/kv/kv-v1.html
> This documentation assumes the kv secrets engine is enabled at the /secret path in Vault. Since it is possible to enable secrets engines at any location, please update your API calls accordingly.

*** 
**[1]**  
> I think the easiest thing to do here would be to simply not add the prefix, leaving to the user the liberty to specify the location.

This seems to be indeed the cleanest and easiest solution. However, it would break existing deployments since an existing server config file would contain a endpoint similar to: `https://<domain>:<port>`. Removing the `kv` prefix would cause requests to fail.

**[2]**  
> Another option would be to add another option to specify this prefix, with "kv" being its default value.

This would work as well but we would add an config option - e.g. `engine` - that seems not necessary. Once it is added we cannot remove it since some deployments would depend on it.

***

Therefore, I propose the following approach based on [1]:
 - Let the user specify the engine as part of the endpoint - e.g `https://<domain>:<port>/<my-engine>`
 - Since there has to be an engine we can auto-complete an endpoint like: `https://<domain>:<port> 
   to `https://<domain>:<port>/kv`.

This approach would work for most cases. However, if Vault runs behind a proxy (nginx etc.) it might
be the case that `https://<domain>:<port>` would resolve to `https://<internal-ip>:<internal-port>/kv`.
In this case, auto-completing the secret name would cause requests to fail. However, since that hasn't been reported, yet, nobody seems to use such a setup, yet. Observe, that such a configuration would not work right now as well.

Therefore, we do the auto-completion but explicitly specify the engine name in the docs and guides.
Once the majority of deployments use an endpoint with an explicit engine name we can actually drop the auto-completion.

**Comment by aead** [comment]
After some more investigation it turns our that the approach described above those not solve the problem sufficiently.
The same issue exists for the authentication engines (i.e. AppRole). Authentication engines can be enabled under arbitrary paths as well. The current code assumes that the AppRole is mounted under `approle`. For reference: https://www.vaultproject.io/api/auth/approle

Therefore, it seems like we have to implement an approach like [2] of https://github.com/minio/kes/issues/55#issuecomment-636463853. So, we need two more configuration options:
```yaml
vault:
     endpoint: ""  # The Vault endpoint - e.g. https://127.0.0.1:8200 
     engine: ""    # The KV engine path - e.g. 'secrets'. If empty, defaults to 'kv'.
     namespace: "" # An optional Vault namespace. See: https://www.vaultproject.io/docs/enterprise/namespaces/index.html
     prefix: ""    # An optional K/V prefix. The server will store keys under this prefix. 
     approle:    # AppRole credentials. See: https://www.vaultproject.io/docs/auth/approle.html
       engine: ""  # The AppRole engine path - e.g. 'authenticate'. If empty, defaults to 'approle'.
       id: ""      # Your AppRole Role ID
       secret: ""  # Your AppRole Secret ID
       retry: 15s  # Duration until the server tries to re-authenticate after connection loss.
```
