### ISSUE TITLE
Policy errors when using config file

### ISSUE THREAD

**Issue by alv16106** [minio/kes#57]
#### Bug describtion
While using KES for docker I always get a "policy does not allow this" error when using a configuration file, this however does not happen when reproducing the same steps in my machine.

This is the docker file i've been using for my tests. I run this docker, copy the cert and key files for the root identity and try to create a key, but I get the mentioned error.

```docker
# minio KES
FROM minio/kes:latest

COPY ./server-config.yaml .

RUN  \
     apk add --no-cache ca-certificates bash openssl 'curl>7.61.0' 'su-exec>=0.2' && \
     rm -rf /var/cache/apk/* && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf


RUN openssl ecparam -genkey -name prime256v1 | openssl ec -out server.key
RUN openssl req -new -x509 -days 30 -key server.key -out server.cert \
  -subj "/C=/ST=/L=/O=/CN=localhost" -addext "subjectAltName = IP:127.0.0.1"
RUN kes tool identity new --key=root.key --cert=root.cert root

CMD ["server", "--root=$(kes tool identity of root.cert)", "--auth=off", "--config=server-config.yaml"]
```

Here is the config file I am using

```yaml
address: 0.0.0.0:7373
root:   enable

tls:
  key:  server.key
  cert: server.cert

policy:
  my-app: 
    paths:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    identities:
    - all

log:
  error: on
  audit: on

keys:
  fs:
    path: ./keys
```

#### Expected behavior
Being able to perform actions

**Comment by aead** [comment]
@alv16106 
Here are some things not quite correct:
1. The root identity (the public key and the corresponding private key) belong to the client - not the KES server. So, this command has to be run on the KES client side of your setup:
```
kes tool identity new --key=root.key --cert=root.cert root
```
However, do you actually need a root identity? Or do you only want identities that have explicit policies?

```yaml
root:   enable
```
An identity is not something you can "enable". 
Same for:
```
identities:
    - all
```
This does not allow "all" identities access to the specified APIs. It would grant an identity that matches the string `all` access to the APIs. Since an identity is a SHA-256 hash an identity will never match `all`. Therefore, your setup cannot work.

Maybe you want to take a look at:
[1]: https://github.com/minio/kes/wiki/Configuration#kes-server
[2]: https://github.com/minio/kes/wiki/Concepts#access-control

**Comment by aead** [comment]
What you need for a minimal working setup is:
 - A private key + certificate for the KES server to expose the API over HTTPS.
 - A client identity. This means you client applications needs a  private key + certificate.

The following config file:
```
address: 0.0.0.0:7373
root:   _ # We don't need root in a minimal setup. Therefore, we specify an identity that is not a SHA-256 hash.

tls:
  key:  server.key
  cert: server.cert

policy:
  my-app: 
    paths:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    identities:
    - ${MY_APP_IDENTITY}

keys:
  fs:
    path: ./keys
```

Let's assume you have a private key and certificate for you client application - i.e. `app.key` and `app.cert`.
Now you have to export the env. var. MY_APP_IDENTITY=$(kes tool identity of app.cert)` at the server - so in the docker container.
Then the container can start the server via:
```
kes server --config=config.yml --auth=off
```

**Comment by alv16106** [comment]
Thanks for the reply!
I've since changed my Dockerfile to look more like this
``` Docker
...
COPY ./server-config.yaml .

COPY ./server.key .

COPY ./server.cert .

COPY ./app.cert .

RUN export APP=$(kes tool identity of app.cert)  

CMD ["kes", "server", "--auth=off", "--config=server-config.yaml"]
```

When I run the image and try to create a key I'm still getting 'prohibited by policy'
This is my config
``` yaml
address: 0.0.0.0:7373
root: _

tls:
  key:  server.key
  cert: server.cert

policy:
  my-app: 
    paths:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    identities:
    - ${APP}

log:
  error: on
  audit: on 

keys:
  fs:
    path: ./keys
```

**Comment by aead** [comment]
How do you try to connect to the KES server?

***

Also, you can insert the identity into the config file directly:
```yaml
identities:
    - <identity-printed-by-kes-tool-identity-of-app.cert>
```
That way you don't have to copy the `app.cert` into the container. But that is just a detail.

**Comment by alv16106** [comment]
> How do you try to connect to the KES server?

I opened another terminal (in my host, not in docker) and used the app.key and app.cert as env variables, then used the command
`kes key create key -k`
> KES server should print an audit event

It did, It printed the identity and error 403
``` json
{"time":"2020-06-17T17:29:23Z","request":{"path":"/v1/key/create/key","identity":"a9f4dd8a93be233a6d33b3d443394441d525f420c4699287aa913c1415ca9973"},"response":{"code":403, "time":18167}}
```

**Comment by aead** [comment]
Okay, then if you run `kes tool identity of app.cert` does it match:
```
kes tool identity of app.cert

  Identity:  a9f4dd8a93be233a6d33b3d443394441d525f420c4699287aa913c1415ca9973
```

Also, does it change anything if you use the following config file:
```yaml
address: 0.0.0.0:7373
root: _

tls:
  key:  server.key
  cert: server.cert

policy:
  my-app: 
    paths:
    - /v1/key/create/*
    - /v1/key/generate/*
    - /v1/key/decrypt/*
    identities:
    - a9f4dd8a93be233a6d33b3d443394441d525f420c4699287aa913c1415ca9973

log:
  error: on
  audit: on 

keys:
  fs:
    path: ./keys
```
